version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: billboard-bee-db
    environment:
      POSTGRES_USER: billboard_bee
      POSTGRES_PASSWORD: billboard_bee
      POSTGRES_DB: billboard_bee
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 