services:
  - type: web
    name: billboard-bee
    runtime: node
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss && npm run seed && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: billboard-bee-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        value: noreply@billboardbee.se
      - key: NEXT_PUBLIC_MAPBOX_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: billboard-bee-db
    databaseName: billboardbee
    user: billboardbee
    plan: starter
    healthCheckPath: /
    autoDeploy: true 